# Generated by Django 4.0.2 on 2022-04-02 02:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phase1',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'Female')], max_length=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Question1', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('Question2', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('Question3', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('Question4', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('Question5', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('Question6', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('Question7', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('Question8', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
            ],
        ),
    ]
