# Generated by Django 4.0.2 on 2022-07-02 04:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='share',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'Female')], max_length=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Location', models.CharField(max_length=1)),
                ('Privacy', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('Story', models.CharField(max_length=30000000000000000000000)),
            ],
        ),
        migrations.DeleteModel(
            name='phase1',
        ),
    ]
