# Generated by Django 4.0.2 on 2022-07-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_share_location_alter_share_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='Location',
            field=models.TextField(max_length=20),
        ),
    ]
