# Generated by Django 4.0.2 on 2022-07-23 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_share_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('text', models.TextField(blank=True)),
                ('Title', models.CharField(max_length=30)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.share')),
            ],
        ),
    ]
