# Generated by Django 4.0.2 on 2022-07-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='Comtot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
