# Generated by Django 4.0.2 on 2022-10-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_share_comtot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Title',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
    ]
